image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: nginx-rpm/rpm-nginx:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
